apiVersion: v1
kind: Service
metadata:
  name: echo-service
  labels:
    app: echo
    svc: test-echo
spec:
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80